-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-04-01 20:35:52 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012
use msdb;
drop database Forex;
create database Forex;
use Forex;

CREATE TABLE accounts (
    id             INTEGER NOT NULL IDENTITY(1,1),
    balance        money,
    currency       VARCHAR(3),
    margin_level   money,
    users_id       INTEGER NOT NULL
);

ALTER TABLE ACCOUNTS ADD constraint accounts_pk PRIMARY KEY CLUSTERED  (ID) 
     WITH (
	   ALLOW_PAGE_LOCKS = ON , 
       ALLOW_ROW_LOCKS = ON );

CREATE TABLE candles 
    (
    id        INTEGER NOT NULL IDENTITY(1,1),
    low       decimal (20, 5),
    high      decimal (20, 5),
    "Open"    decimal (20, 5),
    "Close"   decimal (20, 5),
     Date DATETIME , 
     SYMBOLS_ID INTEGER NOT NULL , 
     INTERVALS_ID INTEGER NOT NULL ); 

ALTER TABLE CANDLES ADD constraint candles_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE intervals (
    id         INTEGER NOT NULL IDENTITY(1,1),
    name       VARCHAR (3),
    duration   time
);

ALTER TABLE INTERVALS ADD constraint intervals_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE orders 
    (
    id     INTEGER NOT NULL IDENTITY(1,1),
    type   VARCHAR (10), 
     Date DATETIME , 
     Stop_Loss decimal(20,5) , 
     Take_Profit decimal(20,5) ,
	 price decimal(20,5),
     ACCOUNTS_ID INTEGER NOT NULL , 
     SYMBOLS_ID INTEGER NOT NULL );

ALTER TABLE ORDERS ADD constraint orders_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE positions 
    ( id INTEGER NOT NULL IDENTITY(1,1), 
     Date DATETIME , 
     Status BIGINT , 
     ORDERS_ID INTEGER NOT NULL 
    );

    


CREATE unique nonclustered index positions__idx ON positions ( orders_id );

ALTER TABLE POSITIONS ADD constraint positions_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE symbols (
    id           INTEGER NOT NULL IDENTITY(1,1),
    name         VARCHAR(10),
    pips_value   decimal(20,5)
);
ALTER TABLE SYMBOLS ADD constraint symbols_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );
CREATE TABLE users (
    id              INTEGER NOT NULL,
    name            VARCHAR (64),
    last_name       VARCHAR (64),
    nationality     VARCHAR (64),
    email           VARCHAR (64),
    mobile_number   VARCHAR (20)
);

ALTER TABLE USERS ADD constraint users_pk PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE ACCOUNTS
    ADD CONSTRAINT accounts_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CANDLES
    ADD CONSTRAINT candles_intervals_fk FOREIGN KEY ( intervals_id )
        REFERENCES intervals ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CANDLES
    ADD CONSTRAINT candles_symbols_fk FOREIGN KEY ( symbols_id )
        REFERENCES symbols ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE ORDERS
    ADD CONSTRAINT orders_accounts_fk FOREIGN KEY ( accounts_id )
        REFERENCES accounts ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE ORDERS
    ADD CONSTRAINT orders_symbols_fk FOREIGN KEY ( symbols_id )
        REFERENCES symbols ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE POSITIONS
    ADD CONSTRAINT positions_orders_fk FOREIGN KEY ( orders_id )
        REFERENCES orders ( id )
ON DELETE NO ACTION 
    ON UPDATE no action 

CREATE SEQUENCE postion_sequence  
    START WITH 1036
    INCREMENT BY 1 ;  

CREATE SEQUENCE order_sequence  
    START WITH 82342
    INCREMENT BY 1 ;  



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
